apiVersion: v1
kind: Pod
metadata:
  name: service-a
spec:
  containers:
  - name: service-a
    image: 282641971624.dkr.ecr.ap-northeast-1.amazonaws.com/take:service-a
  imagePullSecrets:
    - name: ecr-registry-secret